import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import MobileNav from "@/components/MobileNav";
import DesctopNav from "@/components/DesktopNav";
import ThemeObserver from "@/components/ThemeObserver";
import { auth } from "@/auth";
import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode
}>)
{
  const session = await auth();
  if(!session) return redirect('/settings')
  
  return (
    <html lang="en">
      <body
       
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-black`}>
        <Theme>
          {modal}
           <div className="flex min-h-screen dark:bg-gray-950 dark:text-gray-300">
            {session && (
              <DesctopNav />

              )}

                       <div className="lg:pb-4 pb-24 px-4 lg:px-8 pt-4 flex justify-around w-full">
              <div className="w-full">
               {children}
              </div>
            </div>
          </div>
       {session && (
          <MobileNav />

       )}
                  </Theme>
        <ThemeObserver />

      </body>
    </html>
  );
}
